### ISSUE TITLE
Persona

### ISSUE THREAD

**Issue by TheChosenJuanManuel** [Practica2-Ifes/MantenimientoPredictivo#1]
Todos los datos de los tecnicos y administradores que sean comunes a ellos

**Comment by TheChosenJuanManuel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Persona](https://trello.com/c/DnsVtG9g/4-persona)

**Comment by manuromero** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tecnico](https://trello.com/c/KJS8E2gs/32-tecnico)

**Comment by manuromero** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tecnico](https://trello.com/c/KJS8E2gs/32-tecnico)
